### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by aeroneer1** [Shmakov/kroger-cli#1]
Successfully logged in, and shows account info.

But checking points crashes on me:
`Signing in.. (please wait, it might take awhile)
Loading points balance..
Couldn't retrieve the points balance.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "lib\site-packages\pyppeteer\launcher.py", line 151, in _close_process
  File "asyncio\base_events.py", line 591, in run_until_complete
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback`

Coupon clipping gives me a successful clipped message, but then crashes with same error.

Any ideas what's wrong?

**Comment by Shmakov** [comment]
The actual error message is unrelated to the fact that the script `Couldn't retrieve the points balance.`. I think I've introduced that error message in one of the latest releases, I will see how I can fix it.

Usually the points balance in unavailable because the preferred store is not correctly selected.

1) Could you please confirm that you've a correct `domain` in the `config.ini`? E.g. if you shop at Krogers, it should state kroger.com or if you shop at Ralphs, it should say ralphs.com. Feel free to set a correct domain field in the config file and re-run the program.

2) If the above trick doesn't work, could you please send a screenshot of a `[domain.com]/account/pointssummary` page from your web-browser? E.g.: https://www.kroger.com/account/pointssummary

Thank you!

**Comment by aeroneer1** [comment]
Aw, ok this may be the problem. I am trying to use kroger, but actually our points are with King Sooopers; e.g.: kingsoopers.com. 

So I used this in my domain, and now the points report is coming back. But then it still crashes at the end with that message. So now I can successfully load coupons, check points, but at all times I get the error message upon exit.

The survey doesn't seem to be working yet either. It gets to a kingsoopers.com/mypurchases/image/<serial code>, then hangs without loading anything.



Do you know if I can just use that for my domain? Or is it not supported, such as Smiths, etc.

**Comment by Shmakov** [comment]
The correct domain must be set in the config to retrieve points balance. However, for all other functions it will work with any Kroger's domain.

Something is wrong with the survey's you are right, however I think that is temporary issue on the kroger's side. I am myself unable to open the `View Receipt` link from the `Purchase Details` page. That page displays the entry id and the script cannot continue without it. Hopefully that is temporary and will work fine soon.

Thanks for the bug report regarding the initial `Launcher.killChrome` issue. I will try to fix it in the next release.

**Comment by Shmakov** [comment]
Thanks for reporting the bug @aeroneer1!

The original issue has been resolved. Survey bug is out of scope of this issue and related to a krogers website, hopefully will be fixed by them soon. You can download latest version from the [releases](https://github.com/Shmakov/kroger-cli/releases) tab.

The exception had to do with pyppeteer. I've created an [issue in their repository](https://github.com/pyppeteer/pyppeteer/issues/123).
